const fs = require('fs');
require('dotenv').config({ path: '.env.production' });

const config = `// Generated by build.js — do not edit directly
const FIREBASE_CONFIG = {
  apiKey: "${process.env.FIREBASE_API_KEY}",
  authDomain: "${process.env.FIREBASE_PROJECT_ID}.firebaseapp.com",
  databaseURL: "${process.env.FIREBASE_DATABASE_URL}",
  projectId: "${process.env.FIREBASE_PROJECT_ID}",
  storageBucket: "${process.env.FIREBASE_PROJECT_ID}.firebasestorage.app",
  messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  appId: "${process.env.FIREBASE_APP_ID}",
};

const ROUTES = {
  SUN_CITY:   { label: "Sun City",   sub: "Sun Village", icon: "🏘" },
  RUSTENBURG: { label: "Rustenburg", sub: "Town",        icon: "🏙" },
};

function routeLabel(route) {
  const r = ROUTES[route];
  return r ? r.icon + " " + r.label + " (" + r.sub + ")" : route;
}

function timeAgo(ts) {
  const mins = Math.floor((Date.now() - ts) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return mins + "m ago";
  return Math.floor(mins / 60) + "h ago";
}
`;

fs.writeFileSync('public/firebase-config.js', config);
console.log('✅ public/firebase-config.js generated from .env.production');
